# Generated by Django 5.2.8 on 2025-11-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=30)),
                ('manufacture_date', models.IntegerField(max_length=30)),
                ('product_name', models.CharField(max_length=30)),
                ('expiry_date', models.IntegerField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
            ],
        ),
    ]
