# Generated by Django 5.2.8 on 2025-11-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='expiry_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='manufacture_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amazon',
            name='price',
            field=models.IntegerField(),
        ),
    ]
